import { getLanguage, persistLanguage, type AppLanguage, withLanguage } from '../runtime/i18n';
import './style.css';

const root = document.querySelector<HTMLDivElement>('#app')!;
if (!root) throw new Error('Missing #app');
let language: AppLanguage = getLanguage();

const demos = [
  { id:'water', grammar:'EARTH SYSTEM / FLOW', title:{zh:'水循环是怎么运转的？',en:'How does the water cycle work?'}, description:{zh:'把蒸发、水汽输送、降水、地表径流和地下水放进同一套可交互场景。',en:'Follow evaporation, vapor transport, precipitation, runoff and groundwater in one guided scene.'}},
  { id:'eclipse', grammar:'ORBIT / SPATIAL', title:{zh:'为什么会发生日食？',en:'Why does a solar eclipse happen?'}, description:{zh:'用 6 个步骤拆开轨道倾角、交点、对齐、本影和半影。',en:'Break orbital tilt, nodes, alignment, umbra and penumbra into six observable steps.'}},
  { id:'dns', grammar:'FLOW / NETWORK', title:{zh:'DNS 是怎么找到网站的？',en:'How does DNS find a website?'}, description:{zh:'让一次域名查询沿 Resolver、Root、TLD 和权威 DNS 真正跑一遍。',en:'Watch a query move through resolver, root, TLD and authoritative DNS, then return the IP.'}},
  { id:'binary', grammar:'ALGORITHM / PROCESS', title:{zh:'为什么二分查找这么快？',en:'Why is binary search so fast?'}, description:{zh:'每次比较都淘汰一半候选，把“不断砍半”的过程直接可视化。',en:'See every comparison eliminate half the candidates and collapse the search space.'}},
] as const;

const copy = {
  zh:{navDocs:'使用说明',kicker:'CODEX SKILL · THREE.JS · GUIDED EXPLAINERS',titleA:'把知识点，',titleB:'变成真正能讲明白的交互动画。',lead:'步骤导航、主舞台、独立解说和确定性时间轴来自同一份作品。HTML 可以互动，也可以导出 MP4、GIF 和 PNG。',primary:'查看在线实例',secondary:'查看源码',commandLabel:'给 Codex 的一句话',prompt:'$loop-animation\n\n解释水循环。\n\n- 拆成 5 个教学步骤\n- 每一步画面必须发生对应变化\n- 中文 / English 切换\n- 可拖动时间轴\n- 导出 MP4 + GIF',live:'Live Three.js',sectionKicker:'LIVE EXAMPLES',sectionTitle:'先讲清楚，再让动画动起来。',sectionDesc:'每个示例都可以点击步骤、上一页/下一页、播放暂停和拖动时间轴。解释区与动画主舞台彻底分离，不再互相遮挡。',open:'打开交互实例',pipelineKicker:'ONE SOURCE',pipelineTitle:'同一套步骤数据驱动交互、解说与导出。',pipelineLabels:['交互页面','视频','动图','封面'],quickKicker:'QUICK START',quickTitle:'克隆仓库，Codex 直接发现 Skill。',quickDesc:'在仓库中调用 $loop-animation，先生成教学步骤，再构建 Three.js 场景。',footer:'让知识本身动起来。',languageLabel:'EN'},
  en:{navDocs:'Usage',kicker:'CODEX SKILL · THREE.JS · GUIDED EXPLAINERS',titleA:'Turn concepts into',titleB:'interactive animations that actually teach.',lead:'Step navigation, the main stage, explanation panel and deterministic timeline come from one source. Use it as HTML or export MP4, GIF and PNG.',primary:'Explore live demos',secondary:'View source',commandLabel:'One prompt for Codex',prompt:'$loop-animation\n\nExplain the water cycle.\n\n- 5 teachable steps\n- every step must create a matching visual change\n- Chinese / English switch\n- scrub-able timeline\n- export MP4 + GIF',live:'Live Three.js',sectionKicker:'LIVE EXAMPLES',sectionTitle:'Explain first. Animate the mechanism second.',sectionDesc:'Every demo has clickable steps, previous/next navigation, playback and timeline scrubbing. Explanation stays outside the visual stage.',open:'Open interactive',pipelineKicker:'ONE SOURCE',pipelineTitle:'One step model drives interaction, narration and exports.',pipelineLabels:['interactive','video','README','poster'],quickKicker:'QUICK START',quickTitle:'Clone the repo. Codex discovers the Skill.',quickDesc:'Call $loop-animation in the repository: plan teachable steps first, then build the Three.js scene.',footer:'Animate ideas, not text.',languageLabel:'中文'},
} as const;

function demoUrl(id:string,embed=false){const url=new URL(location.href);url.search='';url.searchParams.set('demo',id);if(embed)url.searchParams.set('embed','1');withLanguage(url,language);return url.toString()}
function text<T>(value:{zh:T;en:T}){return value[language]}
function render(){const t=copy[language];document.documentElement.lang=language==='zh'?'zh-CN':'en';root.innerHTML=`
<main class="gallery-shell">
<nav class="gallery-nav"><a class="brand" href="./"><span class="brand-mark"><i></i></span><span>Loop Animation</span></a><div class="nav-links"><a href="#quickstart">${t.navDocs}</a><a href="https://github.com/kevin-luo/loop-animation" target="_blank" rel="noreferrer">GitHub</a><button class="language-switch" id="gallery-language" type="button">${t.languageLabel}</button></div></nav>
<section class="hero"><div class="hero-glow hero-glow--one"></div><div class="hero-glow hero-glow--two"></div><div class="hero-copy"><div class="kicker">${t.kicker}</div><h1>${t.titleA}<br/><span>${t.titleB}</span></h1><p class="hero-lead">${t.lead}</p><div class="hero-actions"><a class="button button--primary" href="#examples">${t.primary}</a><a class="button" href="https://github.com/kevin-luo/loop-animation" target="_blank" rel="noreferrer">${t.secondary}</a></div><div class="hero-proof"><div><b>4</b><span>${language==='zh'?'个可交互实例':'interactive demos'}</span></div><div><b>4</b><span>${language==='zh'?'种输出格式':'output formats'}</span></div><div><b>1</b><span>${language==='zh'?'套教学壳':'guided lesson shell'}</span></div></div></div><div class="hero-stage"><div class="orb orb--a"></div><div class="orb orb--b"></div><div class="orb orb--c"></div><div class="orbit-line orbit-line--a"></div><div class="orbit-line orbit-line--b"></div><div class="hero-terminal"><div class="terminal-top"><span></span><span></span><span></span><b>Codex</b></div><div class="terminal-label">${t.commandLabel}</div><pre><code>${t.prompt}</code></pre></div></div></section>
<section class="showcase" id="examples"><div class="section-heading"><div><span class="section-kicker">${t.sectionKicker}</span><h2>${t.sectionTitle}</h2></div><p>${t.sectionDesc}</p></div><div class="demo-grid">${demos.map((demo,index)=>`<article class="demo-card ${index===0?'demo-card--featured':''}"><div class="demo-frame-wrap"><iframe title="${text(demo.title)}" src="${demoUrl(demo.id,true)}" loading="${index===0?'eager':'lazy'}" tabindex="-1"></iframe><a class="frame-overlay" href="${demoUrl(demo.id)}"></a><span class="live-pill"><i></i>${t.live}</span><span class="demo-number">0${index+1}</span></div><div class="demo-meta"><div class="demo-eyebrow">${demo.grammar}</div><h3>${text(demo.title)}</h3><p>${text(demo.description)}</p><a class="demo-link" href="${demoUrl(demo.id)}">${t.open}<span>↗</span></a></div></article>`).join('')}</div></section>
<section class="pipeline"><div class="section-heading compact"><div><span class="section-kicker">${t.pipelineKicker}</span><h2>${t.pipelineTitle}</h2></div></div><div class="pipeline-row"><div class="pipeline-node pipeline-node--source"><span class="pipeline-dot"></span><strong>Step model</strong><small>renderAt(time)</small></div><div class="pipeline-arrow">→</div><div class="pipeline-node"><strong>HTML</strong><small>${t.pipelineLabels[0]}</small></div><div class="pipeline-node"><strong>MP4</strong><small>${t.pipelineLabels[1]}</small></div><div class="pipeline-node"><strong>GIF</strong><small>${t.pipelineLabels[2]}</small></div><div class="pipeline-node"><strong>PNG</strong><small>${t.pipelineLabels[3]}</small></div></div></section>
<section class="quickstart" id="quickstart"><div class="quickstart-copy"><span class="section-kicker">${t.quickKicker}</span><h2>${t.quickTitle}</h2><p>${t.quickDesc}</p></div><div class="code-panel"><div class="code-top"><span></span><span></span><span></span></div><pre><code>git clone https://github.com/kevin-luo/loop-animation.git\ncd loop-animation\nnpm install\nnpm run dev</code></pre></div></section>
<footer class="gallery-footer"><span>Loop Animation · MIT</span><span>${t.footer}</span></footer></main>`;document.querySelector<HTMLButtonElement>('#gallery-language')?.addEventListener('click',()=>{language=language==='zh'?'en':'zh';persistLanguage(language);const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState({},'',url);render()})}
render();
